bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/CMU_a -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/CMU_a/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/CMU_a/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/CMU_b -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/CMU_b/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/CMU_b/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/Caltech -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Caltech/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Caltech/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/KKI -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/KKI/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/KKI/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/Leuven_1 -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Leuven_1/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Leuven_1/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/Leuven_2 -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Leuven_2/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Leuven_2/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/MaxMun_a -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/MaxMun_a/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/MaxMun_a/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/MaxMun_b -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/MaxMun_b/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/MaxMun_b/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/MaxMun_c -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/MaxMun_c/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/MaxMun_c/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/MaxMun_d -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/MaxMun_d/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/MaxMun_d/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/NYU -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/NYU/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/NYU/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/OHSU -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/OHSU/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/OHSU/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/Olin -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Olin/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Olin/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/Pitt -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Pitt/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Pitt/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/SBL -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/SBL/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/SBL/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/SDSU -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/SDSU/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/SDSU/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/Stanford -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Stanford/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Stanford/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/Trinity -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Trinity/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Trinity/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/UCLA_1 -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/UCLA_1/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/UCLA_1/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/UCLA_2 -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/UCLA_2/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/UCLA_2/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/UM_1 -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/UM_1/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/UM_1/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/UM_2 -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/UM_2/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/UM_2/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/USM -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/USM/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/USM/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts
bidsmri2nidm -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -d /datasets.datalad.org/abide/RawDataBIDS/Yale -o /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Yale/nidm.ttl -log /simple2_NIDM_examples/logs -no_concepts
csv2nidm -csv Phenotypic_V1_0b.csv  -json_map abide_phenotypic_v1_0b_vars_to_terms_v5.json -nidm /simple2_NIDM_examples/datasets.datalad.org/abide/RawDataBIDS/Yale/nidm.ttl -out phenotype.ttl -log /simple2_NIDM_examples/logs -no_concepts